name: Locale generator
on:
  push:
    paths:
      - '**.xml'
    branches: [ main ]
jobs:
  locale_gen:
    name: Generate locales
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
        name: Checkout repository
      - uses: subosito/flutter-action@v2.7.1
        with:
          channel: dev
        name: Switch Flutter channel
      - run: flutter pub get && flutter pub upgrade
        name: Get dependencies
      - run: flutter pub run build_runner build --delete-conflicting-outputs
        name: Generate translations
      - run: git config user.name "dahliaOS-Bot" && git config user.email dahliaosofficial@gmail.com && git add lib/generated && git commit -am "Generated locales" && git push
        name: Push translations
